static const char serverIndex[] PROGMEM = "<!DOCTYPE html>"
"<html>"
  "<head>"
    "<meta charset=\"UTF-8\">"
    "<title>Оновлення прошивки</title>"
    "<style>"
      ":root{--f:22px;}"
      "body{margin:0;background-color:#444;font-family:sans-serif;color:#FFF;}"
      "body,input,button{font-size:var(--f);}"
      "input{width:100%;padding:0.2em;}"
      ".wrp{width:60%;min-width:460px;max-width:600px;margin:auto;margin-bottom:10px;}"
      "h2{color:#FFF;font-size:calc(var(--f)*1.2);text-align:center;margin-top:0.3em;margin-bottom:0.2em;}"
      ".fx{display:flex;flex-wrap:wrap;margin:auto;}"
      ".fx:not(:first-of-type){margin-top:0.3em;}"
      ".fx .fi{display:flex;align-items:center;margin-top:0.3em;width:100%;}"
      ".fx .fi:first-of-type,.fx.fv .fi{margin-top:0;}"
      "input{width:100%;padding:0.1em 0.2em;}"
      "button{width:100%;padding:0.2em;}"
      "a{color:#AAA;}"
      ".sub{text-wrap:nowrap;}"
      ".sub:not(:last-of-type){padding-right:0.6em;}"
      ".ft{margin-top:1em;}"
      ".lnk{margin:auto;color:#AAA;}"
      "@media(max-device-width:800px) and (orientation:portrait){"
        ":root{--f:4vw;}"
        ".wrp{width:94%;max-width:100%;}"
      "}"
    "</style>"
  "</head>"
  "<body>"
    "<div class=\"wrp\">"
      "<h2>ОНОВЛЕННЯ ПРОШИВКИ<div class=\"lnk\" style=\"font-size:50%;\">Розробник: <a href=\"mailto:kurylo.press@gmail.com?subject=Timer Clock\">Дмитро Курило</a></div></h2>"
      "<div class=\"fx\">"
        "<h2>Прошивка:</h2>"
        "<div class=\"fi\">"
          "<form method=\"POST\" action=\"\" enctype=\"multipart/form-data\">"
            "<input type=\"file\" accept=\".bin,.bin.gz\" name=\"firmware\">"
            "<input type=\"submit\" value=\"Завантажити прошивку\">"
          "</form>"
        "</div>"
      "</div>"
      "<div class=\"fx\">"
        "<h2>Файлова система:</h2>"
        "<div class=\"fi\">"
          "<form method=\"POST\" action=\"\" enctype=\"multipart/form-data\">"
            "<input type=\"file\" accept=\".bin,.bin.gz\" name=\"filesystem\">"
            "<input type=\"submit\" value=\"Завантажити файлову систему\">"
          "</form>"
        "</div>"
      "</div>"
      "<div class=\"ft\">"
        "<div class=\"fx\">"
          "<span>"
            "<span class=\"sub\"><a href=\"/\">Назад</a></span>"
          "</span>"
        "</div>"
      "</div>"
    "</div>"
  "</body>"
"</html>";
static const char successResponse[] PROGMEM = "<!DOCTYPE html>"
"<html>"
  "<head>"
    "<meta charset=\"UTF-8\">"
    "<title>Оновлення прошивки</title>"
    "<style>"
      ":root{--f:22px;}"
      "body{margin:0;background-color:#444;font-family:sans-serif;color:#FFF;font-size:var(--f);}"
      ".wrp{width:60%;min-width:460px;max-width:600px;margin:auto;margin-bottom:10px;}"
      "h2{color:#FFF;font-size:calc(var(--f)*1.2);text-align:center;margin-top:0.3em;margin-bottom:0.2em;}"
      "a{color:#AAA;}"
      ".lnk{margin:auto;color:#AAA;}"
      "@media(max-device-width:800px) and (orientation:portrait){"
        ":root{--f:4vw;}"
        ".wrp{width:94%;max-width:100%;}"
      "}"
    "</style>"
  "</head>"
  "<body>"
    "<div class=\"wrp\">"
      "<h2>ОНОВЛЕННЯ ПРОШИВКИ<div class=\"lnk\" style=\"font-size:50%;\">Розробник: <a href=\"mailto:kurylo.press@gmail.com?subject=Timer Clock\">Дмитро Курило</a></div></h2>"
      "<style>"
        "#fill{border:2px solid #FFF;background:#666;margin:1em 0;}#fill>div{width:0;height:2.5vw;background-color:#FFF;animation:fill 15s linear forwards;}"
        "@keyframes fill{0%{width:0;}100%{width:100%;}}"
      "</style>"
      "<div id=\"fill\"><div></div></div>"
      "<script>document.addEventListener(\"DOMContentLoaded\",()=>{setTimeout(()=>{window.location.href=\"/\";},15000);});</script>"
      "<h2>Успішно. Перезавантажуюсь...</h2>"
    "</div>"
  "</body>"
"</html>";